// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpIhcB4niS_w2lOqS5xPaq1hII3LMxehk',
    appId: '1:126672501070:web:40f8983b7ab8c14893861f',
    messagingSenderId: '126672501070',
    projectId: 'simple-messenger-de723',
    authDomain: 'simple-messenger-de723.firebaseapp.com',
    storageBucket: 'simple-messenger-de723.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfxlhDnq7aG3MUItPq29xtBPbboUovWQQ',
    appId: '1:126672501070:android:25e55cd4607af98693861f',
    messagingSenderId: '126672501070',
    projectId: 'simple-messenger-de723',
    storageBucket: 'simple-messenger-de723.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpIhcB4niS_w2lOqS5xPaq1hII3LMxehk',
    appId: '1:126672501070:web:b1db2690c67c539593861f',
    messagingSenderId: '126672501070',
    projectId: 'simple-messenger-de723',
    authDomain: 'simple-messenger-de723.firebaseapp.com',
    storageBucket: 'simple-messenger-de723.firebasestorage.app',
  );
}
